package com.sg.bean.system;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: tb_system_user
 */
@ApiModel(value="com.sg.bean.system.SystemUser")
@Data
public class SystemUser implements Serializable {
    /**
     * 自增id
     *
     * Table:     tb_system_user
     * Column:    id
     * Nullable:  false
     */
    @ApiModelProperty(value="id自增id")
    private Integer id;

    /**
     * 用户名
     *
     * Table:     tb_system_user
     * Column:    username
     * Nullable:  true
     */
    @ApiModelProperty(value="username用户名")
    private String username;

    /**
     * 用户真实姓名
     *
     * Table:     tb_system_user
     * Column:    realname
     * Nullable:  true
     */
    @ApiModelProperty(value="realname用户真实姓名")
    private String realname;

    /**
     * 密码
     *
     * Table:     tb_system_user
     * Column:    password
     * Nullable:  true
     */
    @ApiModelProperty(value="password密码")
    private String password;

    /**
     * 角色 0 管理员 1客服
     *
     * Table:     tb_system_user
     * Column:    role
     * Nullable:  true
     */
    @ApiModelProperty(value="role角色 0 管理员 1客服")
    private String role;

    /**
     * 手机号
     *
     * Table:     tb_system_user
     * Column:    telephone
     * Nullable:  true
     */
    @ApiModelProperty(value="telephone手机号")
    private String telephone;

    /**
     * 性别1男2女
     *
     * Table:     tb_system_user
     * Column:    sex
     * Nullable:  true
     */
    @ApiModelProperty(value="sex性别1男2女")
    private Integer sex;

    /**
     * 创建人ID
     *
     * Table:     tb_system_user
     * Column:    create_by
     * Nullable:  true
     */
    @ApiModelProperty(value="createBy创建人ID")
    private String createBy;

    /**
     * 创建时间
     *
     * Table:     tb_system_user
     * Column:    create_date
     * Nullable:  true
     */
    @ApiModelProperty(value="createDate创建时间")
    private Date createDate;

    /**
     * 最后修改人ID
     *
     * Table:     tb_system_user
     * Column:    update_by
     * Nullable:  true
     */
    @ApiModelProperty(value="updateBy最后修改人ID")
    private String updateBy;

    /**
     * 最后修改时间
     *
     * Table:     tb_system_user
     * Column:    update_date
     * Nullable:  true
     */
    @ApiModelProperty(value="updateDate最后修改时间")
    private Date updateDate;

    /**
     * 备注
     *
     * Table:     tb_system_user
     * Column:    remark
     * Nullable:  true
     */
    @ApiModelProperty(value="remark备注")
    private String remark;

    /**
     * 版本
     *
     * Table:     tb_system_user
     * Column:    version
     * Nullable:  true
     */
    @ApiModelProperty(value="version版本")
    private Integer version;

    /**
     * 数据状态 1正常 0已删除
     *
     * Table:     tb_system_user
     * Column:    state
     * Nullable:  true
     */
    @ApiModelProperty(value="state数据状态 1正常 0已删除")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_system_user
     *
     * @mbg.generated Thu May 07 21:04:39 CST 2020
     */
    private static final long serialVersionUID = 1L;
}