package com.sg.bean.system;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: tb_system_menu
 */
@ApiModel(value="com.sg.bean.system.SystemMenu")
@Data
public class SystemMenu implements Serializable {
    /**
     * id
     *
     * Table:     tb_system_menu
     * Column:    id
     * Nullable:  false
     */
    @ApiModelProperty(value="idid")
    private Integer id;

    /**
     * 编码
     *
     * Table:     tb_system_menu
     * Column:    code
     * Nullable:  true
     */
    @ApiModelProperty(value="code编码")
    private String code;

    /**
     * 名称
     *
     * Table:     tb_system_menu
     * Column:    name
     * Nullable:  true
     */
    @ApiModelProperty(value="name名称")
    private String name;

    /**
     * URL地址
     *
     * Table:     tb_system_menu
     * Column:    url
     * Nullable:  true
     */
    @ApiModelProperty(value="urlURL地址")
    private String url;

    /**
     * 图标
     *
     * Table:     tb_system_menu
     * Column:    icon
     * Nullable:  true
     */
    @ApiModelProperty(value="icon图标")
    private String icon;

    /**
     * 组件
     *
     * Table:     tb_system_menu
     * Column:    component
     * Nullable:  true
     */
    @ApiModelProperty(value="component组件")
    private String component;

    /**
     * 父级权限ID
     *
     * Table:     tb_system_menu
     * Column:    pid
     * Nullable:  true
     */
    @ApiModelProperty(value="pid父级权限ID")
    private String pid;

    /**
     * 创建人ID
     *
     * Table:     tb_system_menu
     * Column:    create_by
     * Nullable:  true
     */
    @ApiModelProperty(value="createBy创建人ID")
    private String createBy;

    /**
     * 创建时间
     *
     * Table:     tb_system_menu
     * Column:    create_date
     * Nullable:  true
     */
    @ApiModelProperty(value="createDate创建时间")
    private Date createDate;

    /**
     * 最后修改人ID
     *
     * Table:     tb_system_menu
     * Column:    update_by
     * Nullable:  true
     */
    @ApiModelProperty(value="updateBy最后修改人ID")
    private String updateBy;

    /**
     * 最后修改时间
     *
     * Table:     tb_system_menu
     * Column:    update_date
     * Nullable:  true
     */
    @ApiModelProperty(value="updateDate最后修改时间")
    private Date updateDate;

    /**
     * 备注
     *
     * Table:     tb_system_menu
     * Column:    remark
     * Nullable:  true
     */
    @ApiModelProperty(value="remark备注")
    private String remark;

    /**
     * 版本
     *
     * Table:     tb_system_menu
     * Column:    version
     * Nullable:  true
     */
    @ApiModelProperty(value="version版本")
    private Integer version;

    /**
     * 数据状态 1正常 0已删除
     *
     * Table:     tb_system_menu
     * Column:    state
     * Nullable:  true
     */
    @ApiModelProperty(value="state数据状态 1正常 0已删除")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_system_menu
     *
     * @mbg.generated Sat May 16 11:38:14 CST 2020
     */
    private static final long serialVersionUID = 1L;
}