package com.sg.bean.system;

import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;

import java.io.Serializable;
import java.util.Date;

/**
 * Table: tb_system_role_menu
 */
@ApiModel(value="com.sg.bean.system.SystemRoleMenu")
@Data
public class SystemRoleMenu implements Serializable {
    /**
     * Table:     tb_system_role_menu
     * Column:    id
     * Nullable:  false
     */
    @ApiModelProperty(value="id")
    private Integer id;

    /**
     * Table:     tb_system_role_menu
     * Column:    role_id
     * Nullable:  false
     */
    @ApiModelProperty(value="roleId")
    private String roleId;

    /**
     * Table:     tb_system_role_menu
     * Column:    menu_id
     * Nullable:  false
     */
    @ApiModelProperty(value="menuId")
    private String menuId;

    /**
     * 创建人ID
     *
     * Table:     tb_system_role_menu
     * Column:    create_by
     * Nullable:  true
     */
    @ApiModelProperty(value="createBy创建人ID")
    private String createBy;

    /**
     * 创建时间
     *
     * Table:     tb_system_role_menu
     * Column:    create_date
     * Nullable:  true
     */
    @ApiModelProperty(value="createDate创建时间")
    private Date createDate;

    /**
     * 最后修改人ID
     *
     * Table:     tb_system_role_menu
     * Column:    update_by
     * Nullable:  true
     */
    @ApiModelProperty(value="updateBy最后修改人ID")
    private String updateBy;

    /**
     * 最后修改时间
     *
     * Table:     tb_system_role_menu
     * Column:    update_date
     * Nullable:  true
     */
    @ApiModelProperty(value="updateDate最后修改时间")
    private Date updateDate;

    /**
     * 备注
     *
     * Table:     tb_system_role_menu
     * Column:    remark
     * Nullable:  true
     */
    @ApiModelProperty(value="remark备注")
    private String remark;

    /**
     * 版本
     *
     * Table:     tb_system_role_menu
     * Column:    version
     * Nullable:  true
     */
    @ApiModelProperty(value="version版本")
    private Integer version;

    /**
     * 数据状态 1正常 0已删除
     *
     * Table:     tb_system_role_menu
     * Column:    state
     * Nullable:  true
     */
    @ApiModelProperty(value="state数据状态 1正常 0已删除")
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_system_role_menu
     *
     * @mbg.generated Fri May 08 16:00:04 CST 2020
     */
    private static final long serialVersionUID = 1L;
}