server:
  port: 8081
  session-timeout: 30
  tomcat.uri-encoding: UTF-8

spring:
  driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:oracle:thin:@10.200.25.38:1521/hydeeBZB
      driver-class-name: oracle.jdbc.OracleDriver
      username: h2
      #配置初始化大小/最小/最大
      initialSize: 10
      minIdle: 10
      maxActive: 50
      #获取连接等待超时时间
      maxWait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      timeBetweenEvictionRunsMillis: 300000
      #一个连接在池中最小生存的时间
      minEvictableIdleTimeMillis: 3600000
      validationQuery: SELECT 1 from dual
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: true
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      poolPreparedStatements: false
      maxPoolPreparedStatementPerConnectionSize: -1
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      web-stat-filter:
        enabled: true
        # url-pattern:
        # exclusions:
        # session-stat-enable: true
        # session-stat-max-count:
        # principal-session-name:
        # principal-cookie-name:
        # profile-enable:
      # StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
      stat-view-servlet:
        enabled: true
        # url-pattern:
        reset-enable: false
        login-username: druid
        login-password: druid

file:
  temp:
    path: D:\fileUpload\
